name: Build and deploy unified Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Login to Azure
        uses: azure/login@v2 #v2 is correct but linter is wrong
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DFC6F559572A43F3A0D597F244FDFEF8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6226BC86134B4F50A6C4E2F89A432435 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0BE9BD7D7AA740EA82548C8F5130B408 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3 #v3 is correct but linter is wrong
        id: deploy-to-webapp
        with:
          app-name: 'dangerous-writing'
          slot-name: 'Production'
          package: .
